### ISSUE TITLE
Any way to perform an action via the api?

### ISSUE THREAD

**Issue by micrb** [dalhundal/sky-q#1]
Hi,

First, thank you for putting this together, I currently use your sky-remote for sky-q and it's great.

Do you know if there is a way to perform an action like open the TV guide via the api?  I have been using wireshark and I can see that if I record something through the sky-q app an action is performed on the box, but that's as far as I've got.

Any help or hints tips would be great.

Cheers.

**Comment by dalhundal** [comment]
Hey - I'm not sure about much yet, early days. I intend to investigate more as I have time, and put anything I can into this module. I just wanted to put this out there even with just it's current function because I know people are looking for a way to tell if the box is on or not.

What do you actually want to achieve if you don't mind me asking?

**Comment by micrb** [comment]
Hi, no worries I appreciate the time you have spent on these.  I have my whole apartment controlled via voice and I can say, "show me what's on" or "display the tv guide" and via your sky-remote tool, I have it executing each command so sendCommand('Guide'), sendCommand('Up') x 10 etc until it shows me the tv guide.  But sometimes the box doesn't catch up with the commands lol and then it goes a bit haywire!  It's very cool though being able to do that.  So I thought if there was a way to executive the command directly, something like http://192.168.2.21:9006/as/pvr/action/tvguide, then the box would just handle that.  But as there isn't a native remote app I can't reverse it.

I'm thinking it must be able to be done, surely sky will replace the sky+ remote with a skyq one?!

Cheers

**Comment by micrb** [comment]
p.s I have been messing with the timings of the commands, they currently sit about 500ms which works 9 out of 10 times I voice control it.

**Comment by dalhundal** [comment]
Ah, I see - you actually want to control the box to tell it to show the TV guide.

There will surely be a way to tell the box to change channel / fast forward + rewind / play a recording etc - but I don't think there will be a way to tell it to open a particular menu or part of the SkyQ interface - the best you can hope for is what you're currently doing, sending out a sequence of remote control commands as if you were pressing buttons on a physical remote.

The Sky+ app couldn't do this either.
